    SELECT U1.ID, CONCAT(U2.FIRST_NAME, ' ', U2.LAST_NAME) AS FULL_NAME, CONCAT('@', U2.LOGIN) AS LOGIN
      FROM USER U1
INNER JOIN FRIENDS F ON F.USER_1 = U1.ID
INNER JOIN USER U2 ON U2.ID = F.USER_2
     WHERE U1.LOGIN = ?

UNION

    SELECT U1.ID, CONCAT(U2.FIRST_NAME, ' ', U2.LAST_NAME) AS FULL_NAME, CONCAT('@', U2.LOGIN) AS LOGIN
      FROM USER U1
INNER JOIN FRIENDS F ON F.USER_2 = U1.ID
INNER JOIN USER U2 ON U2.ID = F.USER_1
     WHERE U1.LOGIN = ?