    SELECT CONCAT(U.FIRST_NAME, ' ', U.LAST_NAME) AS FULL_NAME, CONCAT('@', U.LOGIN) AS LOGIN, U.AGE, U.CITY, U.INTERESTS, ST.VALUE
      FROM USER U
INNER JOIN SEX_TYPE ST ON U.SEX_TYPE_ID = ST.ID
     WHERE LOGIN = ?