SELECT U.ID, CONCAT(U.FIRST_NAME, ' ', U.LAST_NAME) AS FULL_NAME, CONCAT('@', U.LOGIN) AS LOGIN
  FROM USER U
 WHERE U.LAST_NAME LIKE CONCAT(?, '%') AND U.FIRST_NAME LIKE CONCAT(?, '%') AND U.LOGIN != ? AND NOT EXISTS
 (
        SELECT F.USER_2
          FROM USER U1
    INNER JOIN FRIENDS F ON F.USER_1 = U1.ID
         WHERE U1.LOGIN = ? AND F.USER_2 = U.ID

     UNION ALL

        SELECT F.USER_1
          FROM USER U1
    INNER JOIN FRIENDS F ON F.USER_2 = U1.ID
         WHERE U1.LOGIN = ? AND F.USER_1 = U.ID
 )
 LIMIT 5;