SELECT U.ID, CONCAT(U.FIRST_NAME, ' ', U.LAST_NAME) AS FULL_NAME, CONCAT('@', U.LOGIN) AS LOGIN
  FROM USER U
 WHERE U.LOGIN LIKE CONCAT('%', ?, '%') AND U.LOGIN <> ? AND NOT EXISTS
 (
         SELECT U2.ID
           FROM USER U1
     INNER JOIN FRIENDS F ON F.USER_1 = U1.ID
     INNER JOIN USER U2 ON U2.ID = F.USER_2
          WHERE U1.LOGIN = ? AND U2.ID = U.ID

     UNION

         SELECT U2.ID
           FROM USER U1
     INNER JOIN FRIENDS F ON F.USER_2 = U1.ID
     INNER JOIN USER U2 ON U2.ID = F.USER_1
          WHERE U1.LOGIN = ? AND U2.ID = U.ID
 )
 ORDER BY U.LOGIN LIMIT 3